import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from './page.module.css';

const inter = Inter({subsets:['latin']})

export const metadata: Metadata = {
  title: "CloneCoding_Twitter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          {children}
        </div>
      </body>
    </html>
  );
}
